/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package maintainunit;
import java.awt.Frame;
import java.awt.Image;
import java.io.File;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
/**
 *
 * @author MUDITH PRAVEEN
 */
public class Academic extends javax.swing.JFrame {

    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;
    
    String[] itemIdForWork=new String[0];
    String NewItem;
  
    /**
     * Creates new form Academic
     */
    public Academic() {
        initComponents();
        SelectAca();
        SelectInve();
        GetStoreFiter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Mini = new javax.swing.JLabel();
        FullName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Reason = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AcademicTB = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        facalty = new javax.swing.JTextField();
        itemIdWork = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inventoryTBL = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        ItemAddBtn = new javax.swing.JButton();
        Filter2 = new javax.swing.JComboBox<>();
        Filter = new javax.swing.JComboBox<>();
        FilterBtn = new javax.swing.JButton();
        DropStatus = new javax.swing.JComboBox<>();
        StatusBar1 = new javax.swing.JPanel();
        StatusWord1 = new javax.swing.JLabel();
        Clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(185, 173, 17));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Maintain Inventory Management System");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Academic Inventory Request");

        closeBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        closeBtn.setForeground(new java.awt.Color(255, 255, 255));
        closeBtn.setText("X");
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Untitled-3.png"))); // NOI18N

        Mini.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Mini.setForeground(new java.awt.Color(255, 255, 255));
        Mini.setText("-");
        Mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiniMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Mini)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(closeBtn)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Mini, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(57, 16, 49));
        jLabel3.setText("Full Name");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 16, 49));
        jLabel2.setText("ID/ NIC");

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(57, 16, 49));
        jLabel5.setText("Item ID");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(57, 16, 49));
        jLabel6.setText("Reason");

        AddBtn.setBackground(new java.awt.Color(102, 255, 102));
        AddBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        AddBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddBtn.setText("Add");
        AddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBtnMouseClicked(evt);
            }
        });
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setBackground(new java.awt.Color(204, 204, 0));
        UpdateBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        UpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        UpdateBtn.setText("Update");
        UpdateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateBtnMouseClicked(evt);
            }
        });
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setBackground(new java.awt.Color(255, 102, 102));
        DeleteBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBtn.setText("Delete");
        DeleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteBtnMouseClicked(evt);
            }
        });
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        homeBtn.setBackground(new java.awt.Color(57, 16, 49));
        homeBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn.setText("Home");
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        AcademicTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Full Name", "Item ID", "Reason", "Facalty", "Status"
            }
        ));
        AcademicTB.setRowHeight(25);
        AcademicTB.setSelectionBackground(new java.awt.Color(0, 102, 255));
        AcademicTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcademicTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AcademicTB);

        jPanel3.setBackground(new java.awt.Color(185, 173, 17));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(57, 16, 49));
        jLabel7.setText("Facalty");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(57, 16, 49));
        jLabel9.setText("Request Table");

        inventoryTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item ID", "Item Name", "Category", "Store ID"
            }
        ));
        inventoryTBL.setRowHeight(25);
        inventoryTBL.setSelectionBackground(new java.awt.Color(0, 102, 255));
        inventoryTBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryTBLMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(inventoryTBL);

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(57, 16, 49));
        jLabel14.setText("Inventory Table");

        ItemAddBtn.setBackground(new java.awt.Color(102, 255, 102));
        ItemAddBtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        ItemAddBtn.setForeground(new java.awt.Color(255, 255, 255));
        ItemAddBtn.setText("Add");
        ItemAddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemAddBtnMouseClicked(evt);
            }
        });
        ItemAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAddBtnActionPerformed(evt);
            }
        });

        Filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Safety Gear", "Storage Equipment", "Power Tools", "Hand Tools", "Electrical Tools", "Cleaning Supplies", "Landscap Equipment" }));
        Filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterActionPerformed(evt);
            }
        });

        FilterBtn.setBackground(new java.awt.Color(57, 16, 49));
        FilterBtn.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        FilterBtn.setForeground(new java.awt.Color(255, 255, 255));
        FilterBtn.setText("Filter");
        FilterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FilterBtnMouseClicked(evt);
            }
        });
        FilterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterBtnActionPerformed(evt);
            }
        });

        DropStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Returned", "Returned" }));
        DropStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DropStatusMouseClicked(evt);
            }
        });
        DropStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropStatusActionPerformed(evt);
            }
        });

        StatusBar1.setBackground(new java.awt.Color(204, 204, 204));

        StatusWord1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StatusWord1.setForeground(new java.awt.Color(255, 255, 255));
        StatusWord1.setText("Not Selected");

        javax.swing.GroupLayout StatusBar1Layout = new javax.swing.GroupLayout(StatusBar1);
        StatusBar1.setLayout(StatusBar1Layout);
        StatusBar1Layout.setHorizontalGroup(
            StatusBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatusBar1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(StatusWord1)
                .addGap(15, 15, 15))
        );
        StatusBar1Layout.setVerticalGroup(
            StatusBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusBar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StatusWord1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Clear.setBackground(new java.awt.Color(102, 102, 102));
        Clear.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(StatusBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DropStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(FullName, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Reason, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ID, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(facalty, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(itemIdWork, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))))
                                .addGap(27, 27, 27)
                                .addComponent(ItemAddBtn))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(AddBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Clear))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(homeBtn)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(49, 49, 49)
                        .addComponent(Filter2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Filter, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FilterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemAddBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemIdWork, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Reason, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(FilterBtn)
                                .addGap(24, 24, 24)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Filter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Filter2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facalty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 50, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StatusBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DropStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddBtn)
                            .addComponent(UpdateBtn)
                            .addComponent(DeleteBtn)
                            .addComponent(Clear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeBtn)
                        .addGap(12, 12, 12))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void SelectAca()
    {
        try{
            Con = DriverManager.getConnection("jdbc:derby://localhost:1527/maintainUnitDB","User1","1234");
            St = Con.createStatement();
            Rs = St.executeQuery("select * from ACADEMICTB");
            AcademicTB.setModel(DbUtils.resultSetToTableModel(Rs));
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    public void SelectInve()
    {
        try{
            Con = DriverManager.getConnection("jdbc:derby://localhost:1527/maintainUnitDB","User1","1234");
            St = Con.createStatement();
            Rs = St.executeQuery("select ITEMID,ITEMNAME,CATEGORY,STOREID from INVENTORY where STATUS='Available'");
            inventoryTBL.setModel(DbUtils.resultSetToTableModel(Rs));
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    private void GetStoreFiter()
    {
        try{
            Con = DriverManager.getConnection("jdbc:derby://localhost:1527/maintainUnitDB","User1","1234");
            St = Con.createStatement();
            String Query = "Select * from User1.STORETD";
            Rs=St.executeQuery(Query);
            Filter2.addItem("All");
            while(Rs.next()){
                String MyStore = Rs.getString("STOREID");
                Filter2.addItem(MyStore);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    public void StatusMeth(String x)
    {
        String S=null;
        try{
            Con = DriverManager.getConnection("jdbc:derby://localhost:1527/maintainUnitDB","User1","1234");
            PreparedStatement ad = Con.prepareStatement("select STATUS from ACADEMICTB where ID=?");
            ad.setString(1,x);
            Rs = ad.executeQuery();
            while(Rs.next()){
                S = Rs.getString("status");
            }
            if(S.equals("Not Returned")){
                
                StatusBar1.setBackground(new java.awt.Color(255,0,0,255));
                StatusWord1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                StatusWord1.setForeground(new java.awt.Color(255, 255, 255));
                StatusWord1.setText("Not Returned");
                
            }else{
                if(S.equals("Returned")){
                    StatusBar1.setBackground(new java.awt.Color(0,255,0,255));
                    StatusWord1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                    StatusWord1.setForeground(new java.awt.Color(255, 255, 255));
                    StatusWord1.setText("Returned");
                }
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    private void Clear(){
        ID.setText("");
        itemIdWork.setText("");
        FullName.setText("");
        Reason.setText("");
        facalty.setText("");
    }
    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void AddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtnMouseClicked

        try{
            Con = DriverManager.getConnection("jdbc:derby://localhost:1527/maintainUnitDB","User1","1234");
            PreparedStatement add = Con.prepareStatement("insert into ACADEMICTB values(?,?,?,?,?,?)");
            add.setString(1,ID.getText());
            add.setString(2,FullName.getText());
            add.setString(3,itemIdWork.getText());
            add.setString(4,facalty.getText());
            add.setString(5,Reason.getText());
            add.setString(6,DropStatus.getSelectedItem().toString());
            int row = add.executeUpdate();
            String a =ID.getText();
            String b = FullName.getText();
            String x = a+"/ "+b;
            if(DropStatus.getSelectedItem().toString()=="Returned"){
                    int L = itemIdForWork.length;
                    for(int i=0; i<L; i++){
                    
                        PreparedStatement Ad2 = Con.prepareStatement("update User1.INVENTORY set STATUS='Available',LOCATION='No One Taken',TAKE_BY='No One Taken' where ITEMID=?");
                        Ad2.setString(1,itemIdForWork[i]);
                        Ad2.executeUpdate();
                        

                    }
                }
                if(DropStatus.getSelectedItem().toString()=="Not Returned"){
                    int L = itemIdForWork.length;
                    for(int i=0; i<L; i++){
                    
                        PreparedStatement Ad2 = Con.prepareStatement("update User1.INVENTORY set STATUS='Unavailable',LOCATION=?,TAKE_BY=? where ITEMID=?");
                        Ad2.setString(1,facalty.getText());
                        Ad2.setString(2,x);
                        Ad2.setString(3,itemIdForWork[i]);
                        Ad2.executeUpdate();
                      
                    }
                }
            JOptionPane.showMessageDialog(this, "Item Successfully Added!");
            Con.close();
            SelectAca();
            SelectInve();
            Clear();
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_AddBtnMouseClicked

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtnActionPerformed

    private void UpdateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateBtnMouseClicked
        if(ID.getText().isEmpty()||FullName.getText().isEmpty()||itemIdWork.getText().isEmpty()||facalty.getText().isEmpty()||Reason.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Missing Information!");
        }
        else{
            try{
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/maintainUnitDB","User1","1234");
                PreparedStatement Ad = Con.prepareStatement("update User1.ACADEMICTB set NAME=?,ITEMID=?,FACALTY=?,REASON=?,STATUS=? where ID=?");
                Ad.setString(1,FullName.getText());
                Ad.setString(2,itemIdWork.getText());
                Ad.setString(3,facalty.getText());
                Ad.setString(4,Reason.getText());
                Ad.setString(5,DropStatus.getSelectedItem().toString());
                Ad.setString(6,ID.getText());
                Ad.executeUpdate();
                String S1 = itemIdWork.getText();
                String S2 = S1.replace(" ", "");
                String[] Arr = S2.split(",");
                
                String a =ID.getText();
                String b = FullName.getText();
                String x = a+"/ "+b;
                if(DropStatus.getSelectedItem().toString()=="Returned"){
                    int L = Arr.length;
                    for(int i=0; i<L; i++){
                    
                        PreparedStatement Ad2 = Con.prepareStatement("update User1.INVENTORY set STATUS='Available',LOCATION='No One Taken',TAKE_BY='No One Taken' where ITEMID=?");
                        Ad2.setString(1,Arr[i]);
                        Ad2.executeUpdate();
                    }
                }
                if(DropStatus.getSelectedItem().toString()=="Not Returned"){
                    int L = Arr.length;
                    for(int i=0; i<L; i++){
                    
                        PreparedStatement Ad2 = Con.prepareStatement("update User1.INVENTORY set STATUS='Unavailable',LOCATION=?,TAKE_BY=? where ITEMID=?");
                        Ad2.setString(1,facalty.getText());
                        Ad2.setString(2,x);
                        Ad2.setString(3,Arr[i]);
                        Ad2.executeUpdate();
                      
                    }
                }
                JOptionPane.showMessageDialog(this,"Request Updated Successfully!");
                SelectAca();
                SelectInve();
                Clear();
            }catch(Exception e)
            {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_UpdateBtnMouseClicked

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void DeleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteBtnMouseClicked
        if(ID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Enter The Request Id to be Deleted");
        }
        else{
            try{
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/maintainUnitDB","User1","1234");
                String Id = ID.getText();
                PreparedStatement Add = Con.prepareStatement("DELETE FROM User1.ACADEMICTB where ID=?");
                Add.setString(1,Id);
                Add.executeUpdate();
                String S1 = itemIdWork.getText();
                String S2 = S1.replace(" ", "");
                String[] Arr = S2.split(",");
                int L = Arr.length;
                    for(int i=0; i<L; i++){
                    
                        PreparedStatement Ad2 = Con.prepareStatement("update User1.INVENTORY set STATUS='Available',LOCATION='No One Taken',TAKE_BY='No One Taken' where ITEMID=?");
                        Ad2.setString(1,Arr[i]);
                        Ad2.executeUpdate();
                    }
                SelectAca();
                SelectInve();
                Clear();
                JOptionPane.showMessageDialog(this,"Request Deleted Successfully");
            }catch(SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_DeleteBtnMouseClicked

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnMouseClicked

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeBtnActionPerformed

    private void AcademicTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcademicTBMouseClicked
        DefaultTableModel model = (DefaultTableModel)AcademicTB.getModel();
        int Myindex = AcademicTB.getSelectedRow();
        ID.setText(model.getValueAt(Myindex, 0).toString());
        FullName.setText(model.getValueAt(Myindex, 1).toString());
        itemIdWork.setText(model.getValueAt(Myindex, 2).toString());
        Reason.setText(model.getValueAt(Myindex, 4).toString());
        facalty.setText(model.getValueAt(Myindex, 3).toString());
        String S = AcademicTB.getValueAt(Myindex, 0).toString();
        StatusMeth(S);
    }//GEN-LAST:event_AcademicTBMouseClicked

    private void inventoryTBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryTBLMouseClicked
        DefaultTableModel model = (DefaultTableModel)inventoryTBL.getModel();
        int Myindex = inventoryTBL.getSelectedRow();
        NewItem = inventoryTBL.getValueAt(Myindex, 0).toString();

    }//GEN-LAST:event_inventoryTBLMouseClicked

    private void ItemAddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemAddBtnMouseClicked
        ArrayList<String>arrayList = new ArrayList<String>(Arrays.asList(itemIdForWork));
        arrayList.add(NewItem);
        itemIdForWork = arrayList.toArray(itemIdForWork);
        String s1 = Arrays.toString(itemIdForWork);
        String s2 = s1.replace("[", "");
        String s3 = s2.replace("]", "");
        itemIdWork.setText(s3);
    }//GEN-LAST:event_ItemAddBtnMouseClicked

    private void ItemAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAddBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemAddBtnActionPerformed

    private void FilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FilterActionPerformed

    private void FilterBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FilterBtnMouseClicked

        if(Filter.getSelectedItem().toString()=="All" && Filter2.getSelectedItem().toString()=="All"){
            try{
                Con = DriverManager.getConnection("jdbc:derby://localhost:1527/maintainUnitDB","User1","1234");
                St = Con.createStatement();
                Rs = St.executeQuery("select ITEMID,ITEMNAME,CATEGORY,STOREID from INVENTORY where STATUS='Available'");
                inventoryTBL.setModel(DbUtils.resultSetToTableModel(Rs));
            }catch(SQLException e){
                e.printStackTrace();
            }
        }else{
            if(Filter2.getSelectedItem().toString()=="All"){
                try{
                    Con = DriverManager.getConnection("jdbc:derby://localhost:1527/maintainUnitDB","User1","1234");
                    St = Con.createStatement();
                    Rs = St.executeQuery("select ITEMID,ITEMNAME,CATEGORY,STOREID from INVENTORY where STATUS='Available' and CATEGORY='"+Filter.getSelectedItem().toString()+"'");
                    inventoryTBL.setModel(DbUtils.resultSetToTableModel(Rs));
                }catch(SQLException e){
                    e.printStackTrace();
                }
            }else{
                if(Filter.getSelectedItem().toString()=="All"){
                    try{
                        Con = DriverManager.getConnection("jdbc:derby://localhost:1527/maintainUnitDB","User1","1234");
                        St = Con.createStatement();
                        Rs = St.executeQuery("select ITEMID,ITEMNAME,CATEGORY,STOREID from INVENTORY where STATUS='Available' and STOREID='"+Filter2.getSelectedItem().toString()+"'");
                        inventoryTBL.setModel(DbUtils.resultSetToTableModel(Rs));
                    }catch(SQLException e){
                        e.printStackTrace();
                    }
                }
                else{
                    try{
                        Con = DriverManager.getConnection("jdbc:derby://localhost:1527/maintainUnitDB","User1","1234");
                        St = Con.createStatement();
                        Rs = St.executeQuery("select ITEMID,ITEMNAME,CATEGORY,STOREID from INVENTORY where STATUS='Available' and STOREID='"+Filter2.getSelectedItem().toString()+"'"+" and CATEGORY='"+Filter.getSelectedItem().toString()+"'");
                        inventoryTBL.setModel(DbUtils.resultSetToTableModel(Rs));
                    }catch(SQLException e){
                        e.printStackTrace();
                    }
                }
            }

        }

    }//GEN-LAST:event_FilterBtnMouseClicked

    private void FilterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FilterBtnActionPerformed

    private void DropStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DropStatusMouseClicked

    }//GEN-LAST:event_DropStatusMouseClicked

    private void DropStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropStatusActionPerformed

    }//GEN-LAST:event_DropStatusActionPerformed

    private void ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseClicked
        ID.setText("");
        itemIdWork.setText("");
        FullName.setText("");
        Reason.setText("");
        facalty.setText("");
    }//GEN-LAST:event_ClearMouseClicked

    private void MiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiniMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MiniMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Academic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Academic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Academic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Academic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Academic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AcademicTB;
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton Clear;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JComboBox<String> DropStatus;
    private javax.swing.JComboBox<String> Filter;
    private javax.swing.JComboBox<String> Filter2;
    private javax.swing.JButton FilterBtn;
    private javax.swing.JTextField FullName;
    private javax.swing.JTextField ID;
    private javax.swing.JButton ItemAddBtn;
    private javax.swing.JLabel Mini;
    private javax.swing.JTextField Reason;
    private javax.swing.JPanel StatusBar1;
    private javax.swing.JLabel StatusWord1;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JTextField facalty;
    private javax.swing.JButton homeBtn;
    private javax.swing.JTable inventoryTBL;
    private javax.swing.JTextField itemIdWork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
